### ISSUE TITLE
[Bug] Securing Temporal App Data With Java course incorrect instructions

### ISSUE THREAD

**Issue by mdcarlson** [temporalio/edu-appdatasec-java-code#14]
### Securing Application Data with Java course -- Typos and instruction bugs.

1.  The instructions on setting up the Java environment refer to an incorrect exercise (durable execution) instead of to the appdatasec-java-code one.
2. There are two solution components to compile, but the instructions only list one.
3. Exercise 1, Step 1  - temporal cli command is incorrect.  Should be `temporal workflow --env default show -w converter-workflow `

**Comment by MasonEgger** [comment]
Thanks for these! Here's the fixes

1. https://github.com/temporalio/edu-appdatasec-java-content/pull/12 
2. See above. We don't discuss compiling all directories in this section. There are specific instructions in the exercise readme that'll walk you through those as you need to compile them
3. So the `--env default` isn't required, but this is a good callout of us being more explicit. We're going to discuss this internally and address it later

**Comment by mdcarlson** [comment]
The `--env default` was just for me since I was swapping between local and Temporal Cloud which, I think, are at different versions at the moment.

**Comment by mdcarlson** [comment]
The temporal cli commands before and after making the code changes to ConverterWorker and Starter refer to the wrong workflow ID.

I think that the correct cli command should be:

 `temporal workflow show -w codecserver-workflow`

**Comment by mdcarlson** [comment]
4. Exercise 1, Step 7.ii - Compile fails on CustomPayloadCodec.java with error:
```
[ERROR] /xxx/dev/edu-appdatasec-java-code/exercises/custom-converter/practice/src/main/java/customconverter/codec/CustomPayloadCodec.java:[28,29] method map in interface java.util.stream.Stream<T> cannot be applied to given types;
[ERROR]   required: java.util.function.Function<? super io.temporal.api.common.v1.Payload,? extends R>
[ERROR]   found:    no arguments
[ERROR]   reason: cannot infer type-variable(s) R
[ERROR]     (actual and formal argument lists differ in length)
```
